packages:
  - "packages/*"
  - "websites/*"
allowBuilds:
  esbuild: true
overrides:
  "@file-type-mime/file-type-mime": link:packages/file-type-mime
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
- file-type-mime
